version: 1
send_anonymous_usage_stats: true
project_id: "tap-mongodb"
default_environment: dev
environments:
  - name: dev
plugins:
  extractors:
    - name: "tap-mongodb"
      namespace: "tap_mongodb"
      pip_url: -e .
      capabilities:
        - batch
        - state
        - catalog
        - discover
        - about
        - stream-maps
        - test
      settings:
        - name: mongo
          description:
            These props are passed directly to pymongo MongoClient allowing the
            tap user full flexibility not provided in any other Mongo tap.
        - name: mongo_file_location
          description:
            Optional path to a YAML file containing the mongo configuration
            properties.
        - name: stream_prefix
          description:
            Optionally add a prefix for all streams, useful if ingesting
            from multiple shards/clusters via independent tap-mongodb configs.
          value: ""
        - name: optional_replication_key
          description: |
            Make the replication key optional. If set to true, the tap will
            not fail if the replication key is not found in a document.
        - name: is_timestamp_replication_key
          description: |
            This setting allows the tap to use a date-like incremental replication key, 
            such as an usual `updatedAt`column.
          value: False
        - name: database_includes
          description: |
            A list of databases to include. If this is set,
            only the databases in this list will be replicated.
          value: []
        - name: database_excludes
          description: |
            A list of databases to exclude. If this is set,
            all databases except those in this list will be replicated.
          value: []
        - name: collection_excludes
          description: |
            A list of collection name patterns to exclude from schema discovery.
            Patterns can be exact names or use wildcards (e.g., 'user_hourly_activity*').
            If this list is empty, no collections will be excluded.
          value: []
        - name: strategy
          description: |
            If set to true, the tap will infer the schema from a sample of the
            documents in each collection. If set to false, the tap will
            use a default schema for each collection.
          value: raw
          options:
            - label: raw
              value: raw
            - label: envelop
              value: envelop
            - label: infer
              value: infer
        - name: infer_schema_max_docs
          description: |
            The maximum number of documents to use when inferring the schema.
          value: 2000
        - name: max_record_size
          description: |
            Maximum size of a single record in bytes. Records exceeding this size
            will be skipped with a warning. Default is 16MB (16777216 bytes).
          value: 16777216
        - name: batch_size
          description: |
            Number of records to process in each batch. Smaller batches can help
            with memory usage and chunk size limits. Default is 1000.
          value: 1000
        - name: stream_maps
        - name: stream_map_config
        - name: batch_config
      config:
        # All streams will be prefixed with `example_`
        stream_prefix: example_
        # Exclude collections that match patterns like user_hourly_activity
        collection_excludes: ["user_hourly_activity*"]
        # Batch configuration to handle large documents and chunk size limits
        max_record_size: 8388608  # 8MB - reduced from default 16MB
        batch_size: 500  # Reduced batch size for better memory management
        # These are all passed directly through to pymongo MongoClient, ie:
        mongo:
          host: localhost
          port: 27017
          directConnection: true
          readPreference: secondaryPreferred
          username: mongodb
          password: mongodb
          authSource: admin
          authMechanism: SCRAM-SHA-1
          tls: true
      select:
        - "*.*"
      metadata:
        # Example of how to set a replication key for a collection
        # <stream_prefix><db_name>_<collection_name>
        example_mydb_mycollection:
          replication-key: lastUpdatedAt
        example_mydb_myothercollection:
          replication-key: lastUpdatedAt
  loaders:
    - name: target-jsonl
      variant: andyh1203
      pip_url: target-jsonl
